### ISSUE TITLE
Expresión regular del e-mail incorrecta

### ISSUE THREAD

**Issue by ptrinidad** [cefiro-github/splc2017-registration#8]
Acepta un e-mail como soy-malo@eje-del-mal, sin el .xyz

**Comment by cefiro-github** [comment]
Esto pasa por fiarse en bibliotecas de validación externas ;). Que el patrón /[a-z]+@[a-z]+\.[a-z]+/ lo pongan como ejemplo de "custom pattern" de validación de email ya debería haberme hecho sospechar que no estaba incorporado por defecto :D.
